---
# Filters used for triggering apps deployments

# Environments (change in `base` will deploy everywhere)
nuxt:
  - '.github/**' 
  - 'apps/nuxt/**'
payload:
  - '.github/**'
  - 'apps/payload/**'
