packages:
  - apps/*
  - packages/*

catalog:
  "@wisemen/eslint-config-vue": "^1.0.0-next.0"
  "eslint": "^9.17.0"
  "typescript": "5.7.2"
  "vitest": "2.1.8"
  "zod": "3.24.1"
  "@payloadcms/db-mongodb": "3.12.0"
  "@payloadcms/db-postgres": "3.12.0"
  "@payloadcms/next": "3.12.0"
  "@payloadcms/plugin-search": "^3.12.0"
  "@payloadcms/plugin-seo": "^3.12.0"
  "@payloadcms/richtext-lexical": "3.12.0"
  "@payloadcms/richtext-slate": "3.12.0"
  "@payloadcms/storage-s3": "^3.12.0"
  "@payloadcms/ui": "3.12.0"
  "payload": "3.12.0"
