---
  name: Promote to enviroment
  
  on: # yamllint disable-line rule:truthy
    workflow_dispatch:
      inputs:
        environment:
          description: Target environment to deploy TO
          type: environment
          required: true
        source-tag:
          description: Source tag (defaults to previous environment)
          type: string
          required: false
        image-variants:
          description: List of variants (comma separated)
          type: string
          required: true
  jobs:
    promote-to-env:
      uses: wisemen-digital/devops-github-actions/.github/workflows/workflow-promote-to-environment-scaleway.yml@main
      with:
        environment-source: ${{ inputs.source-tag }}
        environment-target: ${{ inputs.environment }}
        image-variants: ${{ inputs.image-variants }}
      secrets: inherit
